In [10]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2,precision=2,linewidth=75)

In [7]:
import pandas as pd
df = pd.read_csv('dlwpt-code-master/data/p1ch4/tabular-wine/winequality-white.csv')

In [8]:
df.head

<bound method NDFrame.head of      fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0      7;0.27;0.36;20.7;0.045;45;170;1.001;3;0.45;8.8;6                                                                                                                     
1     6.3;0.3;0.34;1.6;0.049;14;132;0.994;3.3;0.49;9...                                                                                                                     
2     8.1;0.28;0.4;6.9;0.05;30;97;0.9951;3.26;0.44;1...                                                                                                                     
3     7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4...                                                                                                                     
4     7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4...                                                  

In [9]:
import csv
wine_path = 'dlwpt-code-master/data/p1ch4/tabular-wine/winequality-white.csv'

In [ ]:
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";",
                         skiprows=1)

In [12]:
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [15]:
col_list = next(csv.reader(open(wine_path), delimiter=";"))
col_list

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [16]:
wineq_numpy.shape,len(col_list)

((4898, 12), 12)

In [17]:
wineq = torch.from_numpy(wineq_numpy)

In [21]:
wineq.size(),wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [26]:
data = wineq[:,:-1]
target = wineq[:,-1]
print(data,data.shape)
print(target,target.shape)

tensor([[ 7.00,  0.27,  ...,  0.45,  8.80],
        [ 6.30,  0.30,  ...,  0.49,  9.50],
        ...,
        [ 5.50,  0.29,  ...,  0.38, 12.80],
        [ 6.00,  0.21,  ...,  0.32, 11.80]]) torch.Size([4898, 11])
tensor([6., 6.,  ..., 7., 6.]) torch.Size([4898])


In [29]:
target = target.long()
target,target.dtype

(tensor([6, 6,  ..., 7, 6]), torch.int64)

In [34]:
target.unique()

tensor([3, 4, 5, 6, 7, 8, 9])

In [35]:
target_onehot = torch.zeros(target.shape[0],10)

In [38]:
temp = target.unsqueeze(1)

In [39]:
target_onehot.scatter_(1,temp,1.0)

tensor([[0., 0.,  ..., 0., 0.],
        [0., 0.,  ..., 0., 0.],
        ...,
        [0., 0.,  ..., 0., 0.],
        [0., 0.,  ..., 0., 0.]])

In [43]:
target_onehot[:3],target[:3]

(tensor([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]]),
 tensor([6, 6, 6]))

In [48]:
target_unsqueezed = target.unsqueeze(1)
target_unsqueezed, print(target_unsqueezed.shape)

torch.Size([4898, 1])


(tensor([[6],
         [6],
         ...,
         [7],
         [6]]),
 None)

In [50]:
data_mean = torch.mean(data,dim=0)
data_mean

tensor([6.85e+00, 2.78e-01, 3.34e-01, 6.39e+00, 4.58e-02, 3.53e+01,
        1.38e+02, 9.94e-01, 3.19e+00, 4.90e-01, 1.05e+01])

In [ ]:
data_std = torch.std(data, dim=0)
data_std

tensor([8.44e-01, 1.01e-01, 1.21e-01, 5.07e+00, 2.18e-02, 1.70e+01,
        4.25e+01, 2.99e-03, 1.51e-01, 1.14e-01, 1.23e+00])

In [54]:
data_normalized = (data - data_mean) / data_std
data_normalized

tensor([[ 1.72e-01, -8.18e-02,  ..., -3.49e-01, -1.39e+00],
        [-6.57e-01,  2.16e-01,  ...,  1.34e-03, -8.24e-01],
        ...,
        [-1.61e+00,  1.17e-01,  ..., -9.63e-01,  1.86e+00],
        [-1.01e+00, -6.77e-01,  ..., -1.49e+00,  1.04e+00]])

In [ ]:
bad_indexes = target <= 3
bad_indexes,bad_indexes.dtype,bad_indexes.sum()
#bool values can be added up

(tensor([False, False,  ..., False, False]), torch.bool, tensor(20))

In [58]:
bad_data = data[bad_indexes]
bad_data.shape

torch.Size([20, 11])

In [ ]:
bad_data = data[target <= 3] # 3
mid_data = data[(target > 3) & (target < 7)] # 4 5 6
good_data = data[target >= 7] # 7 8 9

In [61]:
bad_data.shape,mid_data.shape,good_data.shape

(torch.Size([20, 11]), torch.Size([3818, 11]), torch.Size([1060, 11]))

In [63]:
bad_mean = torch.mean(bad_data,dim=0)
mid_mean = torch.mean(mid_data,dim=0)
good_mean = torch.mean(good_data,dim=0)

In [64]:
bad_mean,mid_mean,good_mean

(tensor([7.60e+00, 3.33e-01, 3.36e-01, 6.39e+00, 5.43e-02, 5.33e+01,
         1.71e+02, 9.95e-01, 3.19e+00, 4.75e-01, 1.03e+01]),
 tensor([6.89e+00, 2.82e-01, 3.36e-01, 6.71e+00, 4.78e-02, 3.54e+01,
         1.42e+02, 9.94e-01, 3.18e+00, 4.87e-01, 1.03e+01]),
 tensor([6.73e+00, 2.65e-01, 3.26e-01, 5.26e+00, 3.82e-02, 3.46e+01,
         1.25e+02, 9.92e-01, 3.22e+00, 5.00e-01, 1.14e+01]))

In [67]:
for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
    print('{:2}{:20}{:6.2f}{:6.2f}{:6.2f}'.format(i, *args))

 0fixed acidity         7.60  6.89  6.73
 1volatile acidity      0.33  0.28  0.27
 2citric acid           0.34  0.34  0.33
 3residual sugar        6.39  6.71  5.26
 4chlorides             0.05  0.05  0.04
 5free sulfur dioxide  53.33 35.42 34.55
 6total sulfur dioxide170.60141.83125.25
 7density               0.99  0.99  0.99
 8pH                    3.19  3.18  3.22
 9sulphates             0.47  0.49  0.50
10alcohol              10.34 10.26 11.42


In [68]:
total_sulfur_threshold = 141.83
total_sulfur_data = data[:,6]

In [69]:
predicted_indexes = torch.lt(total_sulfur_data,total_sulfur_threshold)

In [70]:
predicted_indexes

tensor([False,  True,  ...,  True,  True])

In [76]:
predicted_indexes.sum()
#/len(predicted_indexes)

tensor(2727)

In [75]:
actual_indexes = target > 5
actual_indexes.sum()

tensor(3258)

In [84]:
n_match = torch.sum(actual_indexes & predicted_indexes).item()

n_predicted = torch.sum(predicted_indexes).item()

n_actual = torch.sum(actual_indexes).item()

precision = n_match / n_predicted

recall = n_match / n_actual

print(precision)

print(recall)

0.74000733406674
0.6193984039287906


In [80]:
n_match,n_predicted

(2018, 2727)